services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    healthcheck:
      test: pg_isready -h localhost -p 5432 -q -U ${POSTGRES_USERNAME}
      interval: 15s
      timeout: 15s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks:
      - app-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8501:8501"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - OPENAI_KEY=${OPENAI_KEY}
      - APP_PASSWORD=${APP_PASSWORD}
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
