[project]
name = "azai"
version = "0.1.0"
description = "AZAI monorepo workspace"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = ["database", "frontend", "rag"]