[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docling>=2.28.0",
    "tiktoken>=0.9.0",
]



[tool.ruff]
extend = "../pyproject.toml"
